### ISSUE TITLE
How does this work ?

### ISSUE THREAD

**Issue by kezenwa** [rsms/serve-http#1]
Can this act as Replacement for Nginx or Apache web Server ?
Can t be used to Serve files on the Internet.

What's it's PROS and Cons compared to NGINX which is what I currently Use.

Can it be used to Host PHP based websites ?
What other Languages does it support ?
Any Cons of this Server ?
I meant what are it's Limitations ?

Would really love to try this out.

**Comment by rsms** [comment]
> Can this act as Replacement for Nginx or Apache web Server ?
No! Definitely not. This is **not for production** — just runs Node.js’s built-in HTTP server (which is great, but needs to be configured in different ways for production.)

The purpose of this program is to make it easy and safe to start a web server in some directory. It is a single file to make it easy to both copy-paste into projects and depend on via npm.
